### PR TITLE
path to uri

### LINKED ISSUE #44: pass uri instead of path to phantomjs script
cc @atticae per #41

### PR DESCRIPTION
**Pull request by mrhooray**
fixes #44
cc @atticae

### CODE REVIEW

**Comment by atticae** [comment]
Thanks for looking into it so quickly! I just tested this on my machine (Win7) and it failed because it went into the third branch of the toURI() function instead of the second.

Output from gulp.src was

> C:\work\MyProject\MochaTestRunner.html

the second check failed because of the additional regex test. I am not sure what exactly that is supposed to test, but if I omit that and change the line from 

```javascript
} else if (process.platform === 'win32' && /^.:\//.test(path)) {
``` 

to 

```javascript
} else if (process.platform === 'win32') {
```

it works. My guess is you are testing if it is already a valid URI, but doesnt the first if check test for that already?

**Comment by mrhooray** [comment]
it failed because windows uses back slash, i'l just update to only matching the `drive:` part

**Comment by mrhooray** [comment]
@atticae could you test latest master?

**Comment by atticae** [comment]
It fails, I think the url.parse does not output what you expect.

My path (returned from gulp.src) was:

> C:\work\MyProject\MochaTestRunner.html

parsed, i.e. the output of ```url.parse(crossPlatform(path), true)``` was

```
{ protocol: 'c:',
  slashes: null,
  auth: null,
  host: '',
  port: null,
  hostname: '',
  hash: null,
  search: '',
  query: {},
  pathname: '/work/MyProject/MochaTestRunner.html',
  path: '/work/MyProject/MochaTestRunner.html',
  href: 'c:/work/MyProject/MochaTestRunner.html' }
```

Hope this helps, otherwise I will gladly do some more testing.

**Comment by mrhooray** [comment]
hmm, `c:` becomes the protocol.. let me think about this

**Comment by atticae** [comment]
Seems that url.parse already expects a valid URL. You could use https://github.com/ogt/valid-url to check if the input is an URI and if not use something like https://github.com/sindresorhus/file-url to convert it to one. (Haven't used any of them yet, just found them by googling.)

**Comment by mrhooray** [comment]
in fact `c:/work/MyProject/MochaTestRunner.html` is a valid uri given not all uri has to have double slashes
```js
> var url = require('url')
undefined
> url.format({protocol:'c', pathname: '/some/path'})
'c:/some/path'
> url.format({protocol:'c:', pathname: '/some/path'})
'c:/some/path'
```
those modules you mentioned are for different purposes

**Comment by atticae** [comment]
Hm, what about 

> C:\work\MyProject\MochaTestRunner.html

? (with backslashes, as the path comes out of gulp.src) I doubt that's a valid URI. Might work to check the exact input that comes in (without fixing the slashes) and then send that to file-url if it's not a valid URI. From [looking at the module](https://github.com/sindresorhus/file-url/blob/master/index.js) it seems to also convert the slashes, so you wouldn't have to do that yourself if you get a windows path as input.

**Pull request merged**
